#+TITLE: Brainstorming
#+AUTHOR: Alexander Soto
#+CATEGORY: wagetheft
#+TAGS: Write(w) Update(u) Fix(f) Check(c)

* Barriers
** Lack of information
+ If workers do not not know how many hours they worked in a given week, the worker cannot figure out whether they are being paid properly. If a worker cannot testify in court to approximate hours in a given week,they cannot prove liability or damages. A worker's schedule can vary and contributes to lack of information to hours worked.

+ Inconsistent or incomplete information about the employer or company plays a large role of whether or not a workers' wages can be recuperated.
* Ideas
** Location History
Create a web based tool that worker centers can use to turn cell phone location history into court admissible evidence that summarizes a person's time on the job.

*Process*
1. Downloads location data from Google.
2. Load location data to website
3. Website plots locations on map
4. Draw box around worksite
5. Compute

+. Location history is turned on by default and linked to a Google account  rather than a specific phone.
+. Reasonably accurate
+. The tool can be used to corroborate a worker's story

** Worker center application

Create an application to increase the capacity of community based organizations to address workers' issues.

Application is modeled after a "worker center code" model, that allows worker centers who wish to participate in the network to register and are then given a unique code where workers can elect to work with that specific worker center.

*Features:*
+ Tracks worker hours
+ Track wages
+ Locations
+ Breaks
+ Employer information
+ Company information
+ Generate reports and job logs used for the Department of Labor and Attorney General's Office
+ Share information with other workers and worker centers about non-paying jobs or employers who don't pay their workers.
