#+TITLE: Wage Theft Workshop
#+AUTHOR: Alexander Soto
#+CATEGORY: wagetheft
#+TAGS: Write(w) Update(u) Fix(f) Check(c)


The focus of this workshop is to show how wage theft occurs in our communities and to provide a social and digital context to understand this process through gamification and using workers' stories.

+ In a floor or a table a large piece of paper will be the playcenter or the community of focus.
+ Index cards will be labeled with different symbols that represent different forms of communication, places, and workers' stories.
+ Each index card will have a piece of a  worker's story, interactions with people, places.
+ Index cards will provide instructions as to placing a token or counter in the playcenter that is a "digital footprint"

Example: Worker card
Antonio received a text message from Maria.

"Amor! Espero que estes bien en los estados unidos! Ya enviaste el dinero para pagar los estudios de los muchachos? Te amo mucho!"

The player would then place a "counter" or "token" as an indicator of where the player currently is on the playing field  when they received the text message. Optionally, if the player taks an action as in goes to a location to transfer the money or goes to work a physical token will be placed there too.
